.TH "jpeg-recompress" 1 2.6.3 "09 Feb 2023" "User manual"

.SH NAME
jpeg-recompress

.SH DESCRIPTION
Compress JPEGs by re-encoding to the smallest JPEG quality while keeping perceived
visual quality the same and by making sure huffman tables are optimized.
This is a lossy operation, but the images are visually identical and it usually
saves 30-70% of the size for JPEGs coming from a digital camera, particularly DSLRs.
By default all EXIF/IPTC/XMP and color profile metadata is copied over,
but this can be disabled to save more space if desired.

.SH SYNOPSIS
jpeg-recompress [options] image.jpg compressed.jpg

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-accurate\fR
favor accuracy over speed
.TP
\fB\-c\fR, \fB\-\-no-copy\fR
disable copying files that will not be compressed
.TP
\fB\-d\fR, \fB\-\-defish\fR [arg]
set defish strength [0.0]
.TP
\fB\-f\fR, \fB\-\-force\fR
force process
.TP
\fB\-h\fR, \fB\-\-help\fR
output program help
.TP
\fB\-l\fR, \fB\-\-loops\fR [arg]
set the number of runs to attempt [6]
.TP
\fB\-m\fR, \fB\-\-method\fR [arg]
set comparison method to one of 'mpe', 'psnr', 'mse', 'msef', 'cor', 'ssim', 'ms-ssim', 'vifp1', 'smallfry', 'shbad', 'nhw', 'ssimfry', 'ssimshb', 'sum' [sum]
.TP
\fB\-n\fR, \fB\-\-min\fR [arg]
minimum JPEG quality [40]
.TP
\fB\-p\fR, \fB\-\-no-progressive\fR
disable progressive encoding
.TP
\fB\-q\fR, \fB\-\-quality\fR [arg]
set a quality preset: low, medium, high, veryhigh [medium]
.TP
\fB\-r\fR, \fB\-\-ppm\fR
parse input as PPM
.TP
\fB\-s\fR, \fB\-\-strip\fR
strip metadata
.TP
\fB\-t\fR, \fB\-\-target\fR [arg]
set target quality UM [0.76]
.TP
\fB\-x\fR, \fB\-\-max\fR [arg]
maximum JPEG quality [98]
.TP
\fB\-z\fR, \fB\-\-zoom\fR [arg]
set defish zoom [1.0]
.TP
\fB\-Q\fR, \fB\-\-quiet\fR
only print out errors
.TP
\fB\-S\fR, \fB\-\-subsample\fR [arg]
set subsampling method, valid values: 'default', 'disable' [default]
.TP
\fB\-T\fR, \fB\-\-input-filetype\fR [arg]
set input file type to one of 'auto', 'jpeg', 'ppm' [auto]
.TP
\fB\-V\fR, \fB\-\-version\fR
output program version
.TP
\fB\-Y\fR, \fB\-\-ycbcr\fR [arg]
YCbCr jpeg colorspace: 0 - source, >0 - YCrCb, <0 - RGB

.SH EXAMPLES
Default settings:
.PP
.I
jpeg-recompress image.jpg compressed.jpg
.PP
High quality example settings:
.PP
.I
jpeg-recompress --quality high --min 60 image.jpg compressed.jpg
.PP
Slow high quality settings (3-4x slower than above, slightly more accurate):
.PP
.I
jpeg-recompress --accurate --quality high --min 60 image.jpg compressed.jpg
.PP
Use SmallFry instead of SSIM:
.PP
.I
jpeg-recompress --method smallfry image.jpg compressed.jpg
.PP
Use 4:4:4 sampling (disables subsampling):
.PP
.I
jpeg-recompress --subsample disable image.jpg compressed.jpg
.PP
Remove fisheye distortion (Tokina 10-17mm on APS-C @ 10mm):
.PP
.I
jpeg-recompress --defish 2.6 --zoom 1.2 image.jpg defished.jpg
.PP
Read from stdin and write to stdout with '-' as the filename:
.PP
.I
jpeg-recompress - - <image.jpg >compressed.jpg
.PP
Convert RAW to JPEG via PPM from stdin:
.PP
.I
dcraw -w -q 3 -c IMG_1234.CR2 | jpeg-recompress --ppm - compressed.jpg
.PP
Disable progressive mode (not recommended):
.PP
.I
jpeg-recompress --no-progressive image.jpg compressed.jpg
.PP
Disable all output except for errors:
.PP
.I
jpeg-recompress --quiet image.jpg compressed.jpg

.SH NOTES
"Universal Scale" of metrics (UM):
  0.0
  ... (DIRTY) ...
  0.5
  ... (LOW) ...
  0.75
  ... (MEDIUM) ...
  0.875
  ... (SUBHIGH) ...
  0.9375
  ... (HIGH) ...
  0.96875
  ... (VERYHIGH) ...
  1.0
.PP
Trends:

  UM = 0.25 * (sqrt(sqrt(255.0 / MPE)) - 1.0)
  UM = 0.87 * sqrt(PNSR) - 4.70
  UM = 0.5 * (sqrt(sqrt(1.0 / MSEF)) - 1.0)
  UM = 1.0 * cor_sigma(cor_sigma(COR))
  UM = 1.51 * cor_sigma(cor_sigma(cor_sigma(SSIM)))
  UM = 1.59 * cor_sigma(cor_sigma(MS_SSIM))
  UM = 1.06 * cor_sigma(cor_sigma(VIFP1))
  UM = 3.0 * (SMALLFRY * 0.01 - 0.8)
  UM = 1.0 * cor_sigma(sqrt(SHARPENBAD))
  UM = 0.333 * (sqrt(sqrt(1.0 / NHW)) - 1.0)
    cor_sigma(M) = 1.0 - sqrt(1.0 - M * M)

.SH COPYRIGHT
 JPEG-Archive is copyright © 2015 Daniel G. Taylor
 Image Quality Assessment (IQA) is copyright 2011, Tom Distler (http://tdistler.com)
 SmallFry is copyright 2014, Derek Buitenhuis (https://github.com/dwbuiten)
 All rights reserved.

.SH "SEE ALSO"
 jpeg-compare,
 jpeg-hash,
 jpeg-zfpoint,
 webp-compress,
 cjpeg
