.TH "jpeg-hash" 2.5.9 "15 Jan 2023" "User manual"

.SH NAME
jpeg-hash

.SH DESCRIPTION
Create a hash of an image that can be used to compare it to other images quickly.

.SH SYNOPSIS
jpeg-hash [options] image.jpg

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
output program help
.TP
\fB\-s\fR, \fB\-\-size\fR [arg]
set fast comparison image hash size
.TP
\fB\-V\fR, \fB\-\-version\fR
output program version

.SH EXAMPLES
.I
jpeg-hash image.jpg
.SH COPYRIGHT
 JPEG-Archive is copyright © 2015 Daniel G. Taylor
 Image Quality Assessment (IQA) is copyright 2011, Tom Distler (http://tdistler.com)
 SmallFry is copyright 2014, Derek Buitenhuis (https://github.com/dwbuiten)
 All rights reserved.

.SH "SEE ALSO"
 jpeg-compare,
 jpeg-recompress,
 jpeg-zfpoint,
 webp-compress,
 cjpeg

