.TH "jpeg-zfpoint" 1 2.6.2 "08 Feb 2023" "User manual"

.SH NAME
jpeg-zfpoint

.SH DESCRIPTION
Find ZF point of compress JPEGs by re-encoding to the smallest JPEG quality
while keeping perceived visual quality the same and by making sure huffman tables are optimized.
This is a lossy operation, but the images are visually identical and it usually
saves 30-70% of the size for JPEGs coming from a digital camera, particularly DSLRs.
By default all EXIF/IPTC/XMP and color profile metadata is copied over,
but this can be disabled to save more space if desired.

.SH SYNOPSIS
jpeg-zfpoint [options] image.jpg zfpoint.jpg

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-accurate\fR
favor accuracy over speed
.TP
\fB\-c\fR, \fB\-\-no-copy\fR
disable copying files that will not be compressed
.TP
\fB\-d\fR, \fB\-\-defish\fR [arg]
set defish strength [0.0]
.TP
\fB\-h\fR, \fB\-\-help\fR
output program help
.TP
\fB\-l\fR, \fB\-\-loops\fR [arg]
set the number of runs to attempt [6]
.TP
\fB\-n\fR, \fB\-\-min\fR [arg]
minimum JPEG quality [40]
.TP
\fB\-p\fR, \fB\-\-no-progressive\fR
disable progressive encoding
.TP
\fB\-r\fR, \fB\-\-ppm\fR
parse input as PPM
.TP
\fB\-s\fR, \fB\-\-strip\fR
strip metadata
.TP
\fB\-x\fR, \fB\-\-max\fR [arg]
maximum JPEG quality [100]
.TP
\fB\-z\fR, \fB\-\-zoom\fR [arg]
set defish zoom [1.0]
.TP
\fB\-A\fR, \fB\-\-radius\fR [arg]
sharpen radius [2]
.TP
\fB\-Q\fR, \fB\-\-quiet\fR
only print out errors
.TP
\fB\-S\fR, \fB\-\-subsample\fR [arg]
set subsampling method, valid values: 'default', 'disable' [default]
.TP
\fB\-T\fR, \fB\-\-input-filetype\fR [arg]
set input file type to one of 'auto', 'jpeg', 'ppm' [auto]
.TP
\fB\-V\fR, \fB\-\-version\fR
output program version
.TP
\fB\-Y\fR, \fB\-\-ycbcr\fR [arg]
YCbCr jpeg colorspace: 0 - source, >0 - YCrCb, <0 - RGB
.SH EXAMPLES
Default settings:
.PP
.I
jpeg-zfpoint image.jpg zfpoint.jpg

.SH COPYRIGHT
 JPEG-Archive is copyright © 2015 Daniel G. Taylor
 Image Quality Assessment (IQA) is copyright 2011, Tom Distler (http://tdistler.com)
 SmallFry is copyright 2014, Derek Buitenhuis (https://github.com/dwbuiten)
 All rights reserved.

.SH "SEE ALSO"
 jpeg-compare,
 jpeg-hash,
 jpeg-recompress,
 webp-compress,
 cjpeg
